server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    port_in_redirect off;

    location /create-artifact {
        try_files $uri /create-artifact/index.html;
    }

    location /artifact/ {
        try_files $uri $uri/ /__spa-fallback.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}