[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.graphql"

[deploy]
startCommand = "/usr/local/bin/archive-graphql"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
